CREATE TABLE USER
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    PHONE_NUMBER VARCHAR(255),
    USERNAME VARCHAR(255),
    USE_YN BOOLEAN DEFAULT TRUE
);
CREATE UNIQUE INDEX UK_SB8BBOUER5WAK8VYIIY4PF2BX_INDEX_2 ON USER (USERNAME);